### ISSUE TITLE
공통 컴포넌트: User

### ISSUE THREAD

**Issue by seoye0ng** [Next-Study-habjung/OrangeMarket#20]
## 📄 설명

> 공통 컴포넌트 User 제작

## ✔️ TO-DO

- [x] 공통 컴포넌트 User 제작
- [x] user 타입 정의
- [x] 3가지 타입(post/search/follow)

## 🔔 기타 (선택사항)
기타 사항을 작성해 주세요.
