### ISSUE TITLE
공통 컴포넌트: Header 리팩토링

### ISSUE THREAD

**Issue by seoye0ng** [Next-Study-habjung/OrangeMarket#21]
## 📄 설명

> 공통 컴포넌트 Header 리팩토링

## ✔️ TO-DO

- [x] 경로에 따른 헤더 설정을 위해 headerConfig 제작
- [x] 각 페이지에 맞는 header 추가
- [x] Header icon 클릭 이벤트 기능 추가
  - [x] left icon - 이전으로 가기
  - [x] right icon - 검색, 버튼(저장, 업로드), 더보기 모달
---
- [x] HOC 구조 삭제 
 -> 기존 Header 컴포넌트의 HOC 구조는 다양한 프로퍼티와 동적 컴포넌트를 받아 처리하는 방식으로 설계되어 있었지만, withHeader가 너무 많은 인자를 받아 복잡한 구성 요소를 감싸다 보니, 코드의 흐름이 불분명해지고 복잡도가 높아져 관리가 어려워짐.
 ->
이를 단순화하여 필요 이상의 동적 처리를 줄이는 동시에 HOC를 사용하지 않고 컴포넌트를 바로 작성하여 코드를 직관적으로 만들도록 개선해야 함. (또한 HOC는 매번 새로운 컴포넌트를 반환하는 방식이므로, 불필요한 렌더링 및 성능 저하를 초래할 가능성이 있기 때문에 이를 방지하기 위해 상태와 동작을 명시적으로 관리하는 방향으로 변경할 것. Header에 필요한 데이터를 직접 전달하고 컴포넌트를 조립하는 방식이 더 직관적이며, 추후에 새로운 요구사항이 생기더라도 변경 범위가 좁아 유지보수성이 향상될 것.)

## 🔔 기타 (선택사항)
기타 사항을 작성해 주세요.
