### ISSUE TITLE
페이지 기능: 회원가입 API 연결

### ISSUE THREAD

**Issue by seoye0ng** [Next-Study-habjung/OrangeMarket#24]
## 📄 설명

> 회원가입 페이지 API 연결

## ✔️ TO-DO

- [x] 회원가입 api 연결
- [x] 회원가입 req, res type 정의
- [x] query문 작성
- [x] jest 라이브러리 설치 환경설정
- [x] signup함수 테스트 코드 작성

## 🔔 기타 (선택사항)
기타 사항을 작성해 주세요.
