### ISSUE TITLE
Axios 초기 설정

### ISSUE THREAD

**Issue by seoye0ng** [Next-Study-habjung/OrangeMarket#3]
## 📄 설명

> Axios 초기 설정

## ✔️ TO-DO

- [x] Axios instance 생성
- [x] Axios interseptors 작성
- [x] typescript 적용
- [x] request 메소드 작성

## 🔔 기타 (선택사항)
기타 사항을 작성해 주세요.
