### ISSUE TITLE
리팩토링: 게시물 상세 페이지

### ISSUE THREAD

**Issue by seoye0ng** [Next-Study-habjung/OrangeMarket#37]
## 📄 설명

> 게시물 상세 페이지 리팩토링

## ✔️ TO-DO

- [x] CommentCard
  - [x] commentList 상태를 관리하고, 새로운 댓글이 추가되면 불변성을 유지하면서 기존 commentList에 새 댓글을 추가
  - [x] 기존의 댓글들이 리렌더링되지 않도록 CommentCard에 React.memo를 적용하여 불필요한 렌더링을 방지
- [ ] SearchCommentForm 제작 -> SearchForm과 CommentForm을 재사용 가능한 컴포넌트로 제작 
- [ ] 게시글 시간 표시 -> "분" 단위일 때만 1분마다 업데이트하고, 그렇지 않을 경우 추가적인 업데이트를 하지 않도록 구현

## 🔔 기타 (선택사항)
기타 사항을 작성해 주세요.
