### ISSUE TITLE
페이지 기능: 게시물 상세 API 연결

### ISSUE THREAD

**Issue by seoye0ng** [Next-Study-habjung/OrangeMarket#39]
## 📄 설명

> 게시물 상세 페이지 API 연결

## ✔️ TO-DO

- [x] 게시물 상세 정보 api요청 함수 작성
- [x] 게시물 상세 정보 api요청 쿼리훅 구현
- [x] 댓글리스트 api요청 함수 작성
- [x] 댓글리스트 api요청 쿼리훅 작성
- [x] mocking test 진행

## 🔔 기타 (선택사항)
기타 사항을 작성해 주세요.
