### ISSUE TITLE
리팩토링: routing

### ISSUE THREAD

**Issue by seoye0ng** [Next-Study-habjung/OrangeMarket#45]
## 📄 설명

> routing 리팩토링

## ✔️ TO-DO

- [x] app 폴더는 라우팅 개념으로만 유지하기
  - [x] pages 폴더 생성 후 각각의 페이지 컨텐츠는 pages 폴더에서 관리
- [x] 반복되는 라우터 이동하는 로직들 하나로 관리하기

## 🔔 기타 (선택사항)
기타 사항을 작성해 주세요.
