### ISSUE TITLE
페이지 UI: Splash

### ISSUE THREAD

**Issue by seoye0ng** [Next-Study-habjung/OrangeMarket#47]
## 📄 설명

> Splash 페이지 UI 제작

## ✔️ TO-DO

- [x] Splash 컴포넌트 제작
- [x] Splash 화면 구현
- [x] Splash 애니메이션 구현

## 🔔 기타 (선택사항)
기타 사항을 작성해 주세요.
