### ISSUE TITLE
페이지 UI: RequiredLogin

### ISSUE THREAD

**Issue by seoye0ng** [Next-Study-habjung/OrangeMarket#49]
## 📄 설명

> RequiredLogin 페이지 UI 구현

## ✔️ TO-DO

- [x] SocialLogin 컴포넌트 제작
- [x] 공통 컴포넌트 TextButton 컴포넌트 제작
- [x] Splash 애니메이션(Logo,LogoFont)이 끝나면 BottomSheet가 렌더링 되면서 Splash 컴포넌트(크기 축소, 위치 변경) 및 배경 애니메이션되도록 구현

## 🔔 기타 (선택사항)
기타 사항을 작성해 주세요.
