### ISSUE TITLE
공통 컴포넌트: Header

### ISSUE THREAD

**Issue by seoye0ng** [Next-Study-habjung/OrangeMarket#5]
## 📄 설명

> 공통 컴포넌트 Header 제작

## ✔️ TO-DO

- [x] Header 아이콘 컴포넌트 제작
- [x] Header 컴포넌트 레이아웃 구현
- [x] icon 클릭시 색상 변경
- [x] 타입 정의

## 🔔 기타 (선택사항)
기타 사항을 작성해 주세요.
