### ISSUE TITLE
페이지 기능: 프로필 페이지 리팩토링, 기능 추가

### ISSUE THREAD

**Issue by seoye0ng** [Next-Study-habjung/OrangeMarket#56]
## 📄 설명

> 프로필 페이지 리팩토링 및 기능 추가

## ✔️ TO-DO

- [x] UserInfoSection 
  - [x] 프로필 수정, 상품 등록, 팔로워, 팔로잉 버튼 클릭시 페이지 이동
  - [x] 컴포넌트 분리(주요 기능별로 컴포넌트를 분리)
    - [x] 프로필 이미지 및 팔로우 통계: UserHeader
    - [x] 사용자 텍스트 정보(이름, 소개 등): UserDetails
    - [x] 액션 버튼(팔로우/언팔로우, 네비게이션 버튼): UserActions
      - [x] 내 프로필인지 상대방 프로필인지 구분 
- [ ] 팔로우 언팔로우 기능 구현
- [ ] 팔로우 언팔로우 시 팔로워 카운트 반영
- [ ] 등록된 상품 없을 경우 렌더링X
## 🔔 기타 (선택사항)
기타 사항을 작성해 주세요.
